name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git fetch --prune --unshallow
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.7
    - name: Deploy
      run: mvn  -B -e --settings settings.xml deploy
      env:
          GITHUB_USERNAME: harmanpa
          GITHUB_PASSWORD: ${{ secrets.GH }}
    - name: Job Failed Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_COLOR: '#ff0000'
        SLACK_TITLE: 'jgeom Build Failed'
        SLACK_USERNAME: caebot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_TITLE: 'New build of jgeom'
        SLACK_USERNAME: caeBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
